services:
  # The Express Backend API
  - type: web
    name: trustchain-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PINATA_KEY
        generateValue: true
      - key: PINATA_SECRET
        generateValue: true

  # The React Frontend
  - type: web
    name: trustchain-frontend
    env: static
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_PINATA_API_KEY
        sync: false
      - key: REACT_APP_PINATA_SECRET
        sync: false
      - key: REACT_APP_PINATA_JWT
        sync: false
